name: LuaChineApi

on:
  push:
    branches:
    - master

jobs:
  build:
    name: Build docker image
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Docker build
      run: docker build -t horan/lua-china-api:$GITHUB_SHA .

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: horan
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    - name: Docker push
      run: docker push horan/lua-china-api:$GITHUB_SHA
  
  deploy:
    name: Deploy docker by ssh
    needs: build
    steps:
    - run: ssh root@115.28.82.133 "docker ps"
