name: LuaChineApi

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build docker image
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Change env.lua
      run: sed "s/CLIENT_SECRET = \"\"/CLIENT_SECRET = \"${{secrets.LUA_CHINA_GITHUB_SECRET}}\"/" env.example.lua > env.lua

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: horan/lua-china-api
        registry: docker.io
        tags: $GITHUB_SHA
        username: horan
        password: ${{ secrets.DOCKERHUB_TOKEN }}
  
  deploy:
    runs-on: ubuntu-latest
    name: Deploy docker
    needs: build
    steps:
    - name: ssh pipelines
      uses: cross-the-world/ssh-pipeline@master
      env:
        WELCOME: "ssh pipeline"
      with:
        host: 115.28.82.133
        user: root
        pass: ${{ secrets.SSH_PASSWORD }}
        port: 22
        connect_timeout: 10s
        script: |
          (docker pull horan/lua-china-api:$GITHUB_SHA) && 
          (docker rm -f lua-china-api || true) &&
          docker run -p 10.31.231.178:8887:80 --name=lua-china-api -d horan/lua-china-api:$GITHUB_SHA
