name: LuaChineApi

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build docker image
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Change env.lua
      run: sed -e 's/CLIENT_SECRET = ""/CLIENT_SECRET = "${{secrets.LUA_CHINA_GITHUB_SECRET}}"/' -e 's/password=""/password="${{secrets.MYSQL_PASSWORD}}"/' env.example.lua > env.lua

    - name: Export Date Env
      id: CURRENT_DATE
      run: echo "::set-output name=date::$(TZ=Asia/Shanghai date +'%Y-%m-%d-%H-%M-%S')"

    - name: Build the Docker image
      run: docker build -t ${TKE_IMAGE_URL}:${{steps.CURRENT_DATE.outputs.date}} .

    - name: Login TKE Registry
      run: |
        docker login ${TKE_DOCKER_HUB} --username="${{secrets.TENCENT_CLOUD_ACCOUNT_ID}}" -p "${{ secrets.TKE_REGISTRY_PASSWORD }}"

    - name: Push docker image
      run: |
        docker push ${TKE_IMAGE_URL}:${{steps.CURRENT_DATE.outputs.date}}
  